name: release

on:
  workflow_dispatch: # run manually
  push: # run on matching tags
    tags:
      - '*.*.*'

jobs:
  release-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.14"
      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Build package
        run: uv build
      - name: Publish package to PyPI
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: uv publish
